cookie:
  expiry_days: 30
  key: assinatura_secreta_SPM_criado_por_Ismael_adoro_pizza_la_li_lu_le_lo
  name: cookie_sistema
credentials:
  usernames:
    ismael_adm:
      email: analista.adm@mumix.com.br
      failed_login_attempts: 0
      logged_in: true
      name: Ismael Junior
      password: $2b$12$JcEhH4Pt7rXUEeLc5flGa.7CBFQggGzLkEz60HYVFRxA1hUESWUsG
      role: administrador
    sabrina:
      email: administrativo@mumix.com.br
      logged_in: false
      name: cliente
      password: $2b$12$gHt6hMwM4Kf8m3aEzJ6YKecLLZUpkl15CEk1Fv1woeOPRuYBt47S2
      role: administrador
    usuario_teste:
      email: teste@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: IsmaelTesteUsuario
      password: $2b$12$.3LBUxaJXb.BI/Onf7y7n.crCCm5VP0KIjkEQmE/IACmO01hbmFIi
      role: usuario
preauthorized:
  emails:
  - mels@example.com
