cookie:
  expiry_days: 30
  key: assinatura_secreta_SPM_criado_por_Ismael_adoro_pizza_la_li_lu_le_lo
  name: cookie_sistema
credentials:
  usernames:
    cliente_vip:
      email: cliente@email.com
      failed_login_attempts: 0
      logged_in: false
      name: Cliente VIP
      password: $2b$12$Z1YZKP91fW0kEQoeC0d5j.laCxLnuH238FdloW6ZeKEtWiie1l/5S
      role: usuario
      tag: Palmital
    ismael_adm:
      email: analista.adm@mumix.com.br
      failed_login_attempts: 0
      logged_in: false
      name: Ismael Junior
      password: $2b$12$fkhfbAbpVdFD84/v1gAvcOTojqraFXw91B31oreDqKqM5JweTEiZ6
      role: administrador
    ismael_cliente:
      name: IsmaelTeste
      password: $2b$12$qgt1xZvI5H3hbQRx02MbWecwtF8eBSyAs98EW8uaH4A5Sq4Zs9YtG
      role: usuario
    ismael_usuario:
      name: IsmaelTesteUsuario
      password: $2b$12$D7OYJLXGw1k9FUndcTJgyeKlH7Wj9MkLOsHxXFMs0G91z942/e.OK
      role: usuario
    sabrina:
      email: administrativo@mumix.com.br
      failed_login_attempts: 0
      logged_in: false
      name: cliente
      password: $2b$12$gHt6hMwM4Kf8m3aEzJ6YKecLLZUpkl15CEk1Fv1woeOPRuYBt47S2
      role: administrador
preauthorized:
  emails:
  - mels@example.com
