cookie:
  expiry_days: 30
  key: assinatura_secreta_SPM_criado_por_Ismael_adoro_pizza_la_li_lu_le_lo
  name: cookie_sistema
credentials:
  usernames:
    cliente_Vip:
      email: cliente@email.com
      failed_login_attempts: 0
      logged_in: false
      name: Cliente VIP
      password: $2b$12$P2vP2vP2vP2vP2vP2vP2vP2vP2vP2vP2vP2vP2vP2vP2vP2vP2vP2
      role: cliente
      tag: Palmital
    ismael_adm:
      email: analista.adm@mumix.com.br
      failed_login_attempts: 0
      logged_in: false
      name: Ismael Junior
      password: adm123456
      role: administrador
    sabrina:
      email: administrativo@mumix.com.br
      failed_login_attempts: 0
      logged_in: false
      name: Sabrina
      password: $2b$12$gHt6hMwM4Kf8m3aEzJ6YKecLLZUpkl15CEk1Fv1woeOPRuYBt47S2
      role: usuario
preauthorized:
  emails:
  - mels@example.com
